[package]
name = "host-encode"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
core-protocol = { path = "../core-protocol" }
thiserror = { workspace = true }
tracing = { workspace = true }
libloading = "0.9"
moq-nvenc = "0.1.2"

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
]
