[package]
name = "core-transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
core-protocol = { path = "../core-protocol" }
tokio = { workspace = true }
quinn = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bytemuck = { workspace = true }
